trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'typescript-http'
    verbose: false
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    workingDir: 'typescript-http'
    command: custom
    verbose: false
    customCommand: 'run build'
- task: ArchiveFiles@2
  displayName: 'Archive $(System.DefaultWorkingDirectory)/typescript-http'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/typescript-http'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifact.zip'
    ArtifactName: 'artifact'
- task: Docker@2
  displayName: buildAndPush
  inputs:
    Dockerfile: 'typescript-http/Dockerfile'
    containerRegistry: 'Docker Hub (hirebarend)'
    repository: hirebarend/kvs-typescript-http
    tags: |
     $(Build.BuildId)
     latest